config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  # resources :readings
  resources :users do
    resources :readings
    resources :reports
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :user
  validates_associated :user
  validates_presence_of :value

  # Because we are targeting UTC set created_at time we need to run the conversion to UTC.
  scope :created_today, -> { where('DATE(created_at) = ?', DateTime.now.utc.to_date)  }
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  attr_accessor :readings

  validates_presence_of :report_type, :user_id, :end_date

  def generate
    set_end_date
    readings = get_readings_for_report
    set_values(readings)
    self
  end

  def get_readings_for_report
    self.readings = user.readings.where("DATE(created_at) >= ? AND DATE(created_at) <= ?", self.start_date, self.end_date)
  end

  def set_end_date
    case report_type
    when 'daily'
      self.start_date = self.end_date
    when 'month-to-date'
      self.start_date = self.end_date.beginning_of_month
    when 'monthly'
      self.start_date = self.end_date - 1.month
    end
  end

  def set_values(readings)
    unless readings.empty?
      self.maximum = set_maximum(readings)
      self.minimum = set_minimum(readings)
      self.average = set_average(readings)
    else
      self.maximum = self.minimum = self.average = 0
    end
  end

  def set_maximum(readings)
    readings.map(&:value).max
  end

  def set_minimum(readings)
    readings.map(&:value).min
  end

  def set_average(readings)
    # add all readings together
    readings.map(&:value).reduce(0, :+) / readings.length
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :readings
  has_many :reports

  validate :less_than_four_readings_today
  validates_presence_of :first_name, :last_name

  def full_name
    "#{first_name} #{last_name}"
  end

  def readings_today
    readings.created_today.length
  end

  private
  def less_than_four_readings_today
    if readings_today > 4
      errors.add :readings, "You may only submit four readings today."
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_user

  def index
    readings = User.find(params[:user_id]).readings
    @readings = readings.created_today
  end

  def create
    reading = Reading.new(reading_params)
    if reading.save
      flash[:success] = "Reading successful"
      redirect_to user_readings_path(@user)
    else
      flash[:danger] = reading.errors.full_messages.first
      redirect_to user_readings_path(@user)
    end
  end

  def edit
    render 'readings/index'
  end

  private
  def reading_params
    params.require(:reading).permit([:value, :user_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_user

  def new
    @report = Report.new
  end

  def create
    report = Report.create(report_params)
    report.generate
    if report.save
      redirect_to user_report_path(@user, report)
    end
  end

  def show
    @report = Report.find(params[:id])
  end

  private
  def report_params
    params.require(:report).permit([:end_date, :report_type, :user_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetyCc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1>Sweety - A blood glucose companion.</h1>
        </div>
        <div class="col-md-4">
          <%= link_to "Home", root_path, class: 'btn btn-info', id: 'home-link'%>
        </div>
      </div>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/readings/_form.html.erb
<div>
  <%= form_for :reading , url: { controller: 'readings', action: 'create' } do |f| %>
    <%= f.number_field :value, placeholder: 'mg/dl' %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/readings/index.html.erb
<h3>Dashboard for <%= @user.full_name %></h3>

<div class="row">
  <div class="col-md-4">
    <h4>Today's Readings</h4>
    <ul>
      <% @readings.each do |reading| %>
        <li>
          <%= reading.value %> mg/dl
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-6">
    <% if @readings.count < 4 %>
      <h4>New Reading</h4>
      <%= render 'readings/form', reading: @user.readings.new  %>
    <% end %>
  </div>
</div>

app/views/reports/new.html.erb
<div class="row">
  <h2>Run a report for <%= @user.full_name %></h2>

  <div class="col-md-6">
    <p class='well'>
      <span><strong>Daily:</strong> Data for only selected day.</span><br/>
      <span><strong>Month-to-date:</strong> Data from beginning of month ending on selected day.</span><br/>
      <span><strong>Monthly:</strong> Data from one month (30 days) prior to selected day.</span><br/>
    </p>

  </div>
  <div class="col-md-6">

    <%= form_for @report, url: user_reports_path(@user) do |f| %>

      <%= f.hidden_field :user_id, value: @user.id %>

      <%= f.label :report_type, 'Report Type:' %>
      <%= f.select :report_type, [['Daily', 'daily'], ['Month to Date', 'month-to-date'], ['Monthly', 'monthly']] %><br/>

      <%= f.label :start_date, 'Date:' %>
      <%= f.date_field :end_date, value: Date.today, max: Date.today %><br/>

      <!-- <br/> -->
      <%= f.submit "Run Report", class: 'btn btn-lg' %>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Report Results</h3>
    <p class='well'>
      <span><strong>Report Type:</strong> <%= @report.report_type.humanize %></span><br/>
      <span><strong>Start Date:</strong> <%= @report.start_date %></span><br/>
      <span><strong>End Date:</strong> <%= @report.end_date %></span><br/>
      <span><strong>Max:</strong> <%= @report.maximum %> mg/dl</span><br/>
      <span><strong>Min:</strong> <%= @report.minimum %> mg/dl</span><br/>
      <span><strong>Average:</strong> <%= @report.average %> mg/dl</span><br/>
    </p>

    <%= link_to 'Back', new_user_report_path(@user) %>
  </div>
</div>

app/views/users/index.html.erb
<div class="col-md-6">
  <h3>Current Users</h3>
  <table class='table table-striped table-bordered'>
    <% @users.each do |user| %>
      <tr>
        <td><strong><%= user.full_name %></strong></td>
        <td><%= link_to 'Submit New Readings', user_readings_path(user), id: "readings-link-#{user.id}" %></td>
        <td><%= link_to 'Run Report', new_user_report_path(user), id: "reports-link-#{user.id}" %></td>
       </tr>
    <% end %>
  </table>
</div>